DIV-6140-Sonar warning update
hmcts/div-document-generator-client pull request #372
Opened 2020-09-07 10:38 UTC by madjava

# Description
https://tools.hmcts.net/jira/browse/DIV-6140

Sonar fix to master, updating small fragments of code.

# Checklist:

- [x] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2020-09-07 12:10 UTC, Dizrupto submitted a review, later dismissed

2020-09-07 14:06 UTC, jacmurphy approved these changes

2020-09-07 14:20 UTC, jvictorcf requested changes

2020-09-07 14:20 UTC, jvictorcf commented on src/main/java/uk/gov/hmcts/reform/divorce/documentgenerator/service/impl/EvidenceManagementServiceImpl.java
> +            .orElseThrow(() -> new DocumentStorageException("No document found in response"));
This exception was not part of the original code...
If you decide to add it, can you please write a code to cover this scenario?

2020-09-07 16:06 UTC, madjava commented on src/main/java/uk/gov/hmcts/reform/divorce/documentgenerator/service/impl/EvidenceManagementServiceImpl.java
> +            .orElseThrow(() -> new DocumentStorageException("No document found in response"));
@jacmurphy Updated as discussed with two new scenarios for when response is null and when list is empty. Please re-re-view

2020-09-07 16:16 UTC, jvictorcf requested changes

2020-09-07 16:16 UTC, jvictorcf commented on src/test/java/uk/gov/hmcts/reform/divorce/documentgenerator/service/impl/EvidenceManagementServiceImplUTest.java
> +            MemberMatcher.method(EvidenceManagementServiceImpl.class, "storeDocument",
I don't like this "reflection" way of testing at all and I change it to proper java class tests whenever I come across it.
Feel free to do the same if you see fit.

2020-09-07 16:16 UTC, jvictorcf commented on src/test/java/uk/gov/hmcts/reform/divorce/documentgenerator/service/impl/EvidenceManagementServiceImplUTest.java
> +        verifyPrivate(classUnderTest, Mockito.times(1)).invoke("storeDocument",
Can you please implement the proper mockito verification here?

2020-09-07 16:16 UTC, jvictorcf commented on src/test/java/uk/gov/hmcts/reform/divorce/documentgenerator/service/impl/EvidenceManagementServiceImplUTest.java
> +    public void givenStoreDocumentReturnsEmptyResponse_whenStoreDocumentAndGetInfo_thenThrowDocumentStorageException() throws Exception {
Can you please write a test for when the returned file is an empty array?

2020-09-07 16:16 UTC, jvictorcf commented on src/test/java/uk/gov/hmcts/reform/divorce/documentgenerator/service/impl/EvidenceManagementServiceImplUTest.java
> +    @Test(expected = DocumentStorageException.class)
Also, could you please use assertThrows instead, so that you can assert the message as well as the type of exception?

2020-09-07 16:17 UTC, madjava commented on src/test/java/uk/gov/hmcts/reform/divorce/documentgenerator/service/impl/EvidenceManagementServiceImplUTest.java
> +    public void givenStoreDocumentReturnsEmptyResponse_whenStoreDocumentAndGetInfo_thenThrowDocumentStorageException() throws Exception {
Oh! i guess i should rename test case, its actually testing when returned response is empty array

2020-09-07 16:18 UTC, jvictorcf commented on src/test/java/uk/gov/hmcts/reform/divorce/documentgenerator/service/impl/EvidenceManagementServiceImplUTest.java
> +    public void givenStoreDocumentReturnsEmptyResponse_whenStoreDocumentAndGetInfo_thenThrowDocumentStorageException() throws Exception {
This is testing response as null, right?

2020-09-07 16:18 UTC, madjava commented on src/test/java/uk/gov/hmcts/reform/divorce/documentgenerator/service/impl/EvidenceManagementServiceImplUTest.java
> +            MemberMatcher.method(EvidenceManagementServiceImpl.class, "storeDocument",
the `verifyPrivate` is common in this test class, i reckon there may have been reason why it was implemented this way and using same to maintain similarity.

2020-09-07 16:20 UTC, jvictorcf commented on src/test/java/uk/gov/hmcts/reform/divorce/documentgenerator/service/impl/EvidenceManagementServiceImplUTest.java
> +            MemberMatcher.method(EvidenceManagementServiceImpl.class, "storeDocument",
I reckon it's just the way some previous developers liked it.
I really don't especially because if you rename the method, your tests will start failing.

2020-09-07 16:21 UTC, madjava commented on src/test/java/uk/gov/hmcts/reform/divorce/documentgenerator/service/impl/EvidenceManagementServiceImplUTest.java
> +        verifyPrivate(classUnderTest, Mockito.times(1)).invoke("storeDocument",
Didnt like the look either, its PowerMock which i dont even use, happy to ditch it, just wanted to keep consistency, but seeing we are in agreement not to use it, i will not do so for the test case i have introduced only

2020-09-07 16:27 UTC, madjava commented on src/test/java/uk/gov/hmcts/reform/divorce/documentgenerator/service/impl/EvidenceManagementServiceImplUTest.java
> +    public void givenStoreDocumentReturnsEmptyResponse_whenStoreDocumentAndGetInfo_thenThrowDocumentStorageException() throws Exception {
The previous one test null, this test `Ok` but empty list

2020-09-07 16:28 UTC, madjava commented on src/test/java/uk/gov/hmcts/reform/divorce/documentgenerator/service/impl/EvidenceManagementServiceImplUTest.java
> +            MemberMatcher.method(EvidenceManagementServiceImpl.class, "storeDocument",
I agree

2020-09-08 12:08 UTC, jvictorcf approved these changes

2020-09-08 13:12 UTC, Dizrupto approved these changes

2020-09-08 13:20 UTC, madjava commented
Happy to merge implementation for to fix Sonar errors on master

2020-09-08 13:23 UTC, merged